Support for `DataChain.settings(batch=500)` and `DataChain.batch_map()`
iterative/datachain pull request #191
Opened 2024-07-26 18:37 UTC by dberenbaum

Fixes #84.

I think we should keep open #170. That request seems to be specifically about using futures to batch individual results using the existing `.map` without needing a separate `.batch_map()`. I think `.batch_map()` may be both simpler to implement and explain for now, but I think we could come back to the ideas in #170 in the future.

2024-07-26 19:27 UTC, dmpetrov approved these changes
Great ✨  Thank you Dave for the change!

Shortening the param name - good idea!

2024-07-29 19:31 UTC, rlamy requested changes
This conflates 2 settings that I consider logically unrelated:
1. The size of the input row batches passed to a batched UDF
2. The size of the buffer holding output rows to insert in the warehouse DB

Case 1 needs to be under user control, but case 2 is more of an implementation detail that mostly depends on the warehouse engine. Also, the default value seems OK for case 2 but way too high for case 1.

Exposing case 2 doesn't seem that useful, but it doesn't hurt - as long as it's not conflated with 1. I'd suggest calling it "insert_buffer_size" and keeping "batch" for case 1.

2024-07-29 20:54 UTC, dberenbaum commented
Thanks @rlamy.

I have completely dropped `batch` from `DataChain.settings` since I agree this is not nearly as important and could be confusing alongside `batch_map()`. I was trying to find some usefulness for this already existing setting but in the end I think it's not needed right now.

2024-07-30 12:31 UTC, rlamy approved these changes

2024-07-30 13:53 UTC, merged