session: support disabling temp datasets cleanup on exit via an envvar
iterative/datachain pull request #343
Opened 2024-08-22 15:13 UTC by skshetry

- Adds `DATACHAIN_SESSION_CLEANUP_ON_EXIT` envvar to enable/disable temp datasets cleanup on exit. (by default is enabled).
- Minor refactoring to move environ-related utils to `datachain.environ`. Also added `get_bool_env` which is based on datachain-server's implementation (`default` is renamed to `undefined`).
- Removed unused `get_env_list`.

Related #327.

2024-08-22 15:27 UTC, dreadatour approved these changes
Looks good to me! Thank you for these improvements ❤️

2024-08-22 15:32 UTC, amritghimire approved these changes

2024-08-22 18:31 UTC, shcheklein requested changes
Can we briefly review the expected product behavior on this? It feels we are "hiding" the product issue a bit under this env var. By solving it for a specific `save` we are disable potentially a cleanup of a lot of tables, right?

- How do we save in Studio a dataset returned by query and prevent it from GC?
- Can we do the same for this `save` situation? Can we make `save()` transparent for the Studio logic (`save()` does extra table that is cleaned up, but we also return and somehow in Studio-way save the result as well)?

Sorry if my question a bit of touch - I haven't reviewed the whole code logic for this. I'm primarily coming to this from the product perspective. So, apologies, if I'm missing something obvious here.

2024-08-23 03:31 UTC, skshetry commented
Responded on https://github.com/iterative/datachain/issues/327#issuecomment-2306100171. This `save()` is working as expected.

> How do we save in Studio a dataset returned by query and prevent it from GC?

We create a dataset on a separate prefix on detached queries (i.e. one without save).

https://github.com/iterative/datachain/blob/49141a5b069c7d13d90a1798659faacf494e1e97/src/datachain/dataset.py#L27

Garbage collect only cleans up temporary tables.

https://github.com/iterative/datachain/blob/49141a5b069c7d13d90a1798659faacf494e1e97/src/datachain/data_storage/warehouse.py#L933-L933

https://github.com/iterative/datachain/blob/49141a5b069c7d13d90a1798659faacf494e1e97/src/datachain/data_storage/warehouse.py#L67

https://github.com/iterative/datachain/blob/49141a5b069c7d13d90a1798659faacf494e1e97/src/datachain/data_storage/warehouse.py#L66

2024-08-27 07:05 UTC, closed without merging