remove legacy udf decorator
iterative/datachain pull request #438
Opened 2024-09-13 05:00 UTC by mattseddon

2024-09-13 09:14 UTC, rlamy requested changes
Migrating all those tests is great! However, removing all tar and dir expansion tests is too much, we still need them!

2024-09-13 09:20 UTC, mattseddon commented
> Migrating all those tests is great! However, removing all tar and dir expansion tests is too much, we still need them!

Why?

2024-09-13 09:35 UTC, dreadatour approved these changes
Looks good to me! Thank you! 👍

2024-09-13 09:35 UTC, dreadatour commented on src/datachain/query/udf.py
>  )
```python
from .schema import UDFParameter
```

2024-09-13 09:35 UTC, dreadatour commented on tests/func/test_dataset_query.py
>  )
```python
from datachain.sql.types import String
```

2024-09-13 09:35 UTC, dreadatour commented on tests/func/test_datasets.py
>  )
```python
from datachain.sql.types import Float32
```

2024-09-13 09:35 UTC, dreadatour commented on tests/func/test_dataset_query.py
>  )
```python
from datachain.query import C, DatasetQuery, Object, Stream
```

2024-09-13 11:41 UTC, rlamy commented
> > Migrating all those tests is great! However, removing all tar and dir expansion tests is too much, we still need them!
> 
> Why?

* `test_dir_expansion()` is the only unit-test for that complicated piece of code that's critical for the Unix commands.
* The working tar tests are our only tests of tar file handling
* The xfailing tests for tar support in Unix commands are more debatable: we kept them because we want to support them again eventually.

2024-09-16 01:58 UTC, mattseddon commented
> > > Migrating all those tests is great! However, removing all tar and dir expansion tests is too much, we still need them!
> > 
> > 
> > Why?
> 
> * `test_dir_expansion()` is the only unit-test for that complicated piece of code that's critical for the Unix commands.

It looks like the logic under test here is also tested by the following tests:

tests/func/test_catalog.py::test_cp_double_subdir
tests/func/test_catalog.py::test_cp_edatachain_file_options
tests/func/test_catalog.py::test_cp_multi_subdir
tests/func/test_catalog.py::test_cp_root
tests/func/test_catalog.py::test_cp_subdir
tests/func/test_catalog.py::test_cp_symlinks
tests/func/test_catalog.py::test_du
tests/func/test_catalog.py::test_find
tests/func/test_catalog.py::test_find_names_columns
tests/func/test_catalog.py::test_find_names_paths_size_type
tests/func/test_catalog.py::test_ls_glob
tests/func/test_ls.py::test_ls_glob_sub
tests/func/test_ls.py::test_ls_not_a_directory
tests/func/test_ls.py::test_ls_not_found
tests/func/test_ls.py::test_ls_partial_indexing
tests/func/test_ls.py::test_ls_sources
tests/func/test_ls.py::test_ls_sources_scheme_uppercased
tests/test_cli_e2e.py::test_cli_e2e
tests/test_query_e2e.py::test_query_e2e
tests/unit/test_listing.py::test_basic_expansion
tests/unit/test_listing.py::test_list_dir
tests/unit/test_listing.py::test_multilevel_expansion
tests/unit/test_listing.py::test_subdirs
tests/unit/test_listing.py::test_subname_expansion
tests/unit/test_listing.py::test_subtree

I have however updated `create_tar_dataset` to use the new generator function, renamed it to `create_tar_dataset_with_legacy_columns` and reinstated the `test_dir_expansion` test

> * The working tar tests are our only tests of tar file handling (Edit: see [Convert  `index_tar` to a new-style generator #439](https://github.com/iterative/datachain/issues/439))

I am assuming this is covered by the change you made in #440

> * The xfailing tests for tar support in Unix commands are more debatable: we kept them because we want to support them again eventually.

I am not putting any effort into bringing these tests back.

2024-09-16 12:22 UTC, rlamy reviewed
LGTM, except for the issue with `process_tar()`. Great clean-up!

2024-09-16 12:24 UTC, rlamy commented
> I have however updated `create_tar_dataset` to use the new generator function, renamed it to `create_tar_dataset_with_legacy_columns` and reinstated the `test_dir_expansion` test

Thanks!
 
> > * The working tar tests are our only tests of tar file handling (Edit: see [Convert  `index_tar` to a new-style generator #439](https://github.com/iterative/datachain/issues/439))
> 
> I am assuming this is covered by the change you made in #440

Yes, it is.
 
> > * The xfailing tests for tar support in Unix commands are more debatable: we kept them because we want to support them again eventually.
> 
> I am not putting any effort into bringing these tests back.

That's fine, they're probably more trouble than they're worth.

2024-09-16 23:28 UTC, mattseddon commented on src/datachain/lib/tar.py
> +                if entry.isfile():
No, I caught this with `test_dir_expansion` but I've now extended `test_process_and_open_tar`.

2024-09-16 23:29 UTC, mattseddon commented on src/datachain/lib/tar.py
> +    yield file
removed and updated `create_tar_dataset_with_legacy_columns`

2024-09-16 23:30 UTC, mattseddon commented on tests/unit/lib/test_datachain_merge.py
> +        prefix = cloud_test_catalog.partial_path + "/"
[I] make this into a fixture in a follow-up

2024-09-17 00:03 UTC, merged